[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arrow = "57.1.0"
async-trait = "0.1.89"
datafusion = "51.0.0"
datafusion-postgres = "0.13.0"
tokio = "1.48.0"
